[huggingface]
cache_dir = "${HF_HOME:~/.hf-cache}"
text_model = "${TEXT_EMBEDDING_MODEL:intfloat/multilingual-e5-base}"
img_model = "${IMAGE_EMBEDDING_MODEL:Qdrant/resnet50-onnx}"

[grpc]
port = 7860

[logger]
# level = "debug"
pretty_backtrace = true
